include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true

analyzer:
  exclude:
    - "lib/src/core/services/hasura/graphql_api.graphql.dart"
    - "lib/**/*.g.dart"
    - "ios/**"
    - "web/**"
    - "build/**"
    - "assets/**"
    - "android/**"
    - "windows/**"
