
targets:
  $default:
    sources:
      - lib/**
      - lib/schema.graphql
      - $package$
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/src/core/services/hasura/graphql_api.graphql.dart
              schema: lib/schema.graphql
              queries_glob: lib/src/**.graphql

          scalar_mapping:
            - custom_parser_import: 'package:uailist/src/core/services/hasura/parsers/custom_date_parser.dart'
              graphql_type: Date
              dart_type: DateTime

            - custom_parser_import: 'package:uailist/src/core/services/hasura/parsers/custom_timestamptz_parser.dart'
              graphql_type: timestamptz
              dart_type: DateTime
            
            - custom_parser_import: 'package:uailist/src/core/services/hasura/parsers/custom_uuid_parser.dart'
              graphql_type: uuid
              dart_type: String

            - custom_parser_import: 'package:uailist/src/core/services/hasura/parsers/custom_double_parser.dart'
              graphql_type: float8
              dart_type: double

            - custom_parser_import: 'package:uailist/src/core/services/hasura/parsers/custom_citext_parser.dart'
              graphql_type: citext
              dart_type: String

            - custom_parser_import: 'package:uailist/src/core/services/hasura/parsers/custom_jsonb_parser.dart'
              graphql_type: jsonb
              dart_type: Map
            
            - custom_parser_import: 'package:uailist/src/core/services/hasura/parsers/custom_bigint_parser.dart'
              graphql_type: bigint
              dart_type: double

            - custom_parser_import: 'package:uailist/src/core/services/hasura/parsers/custom_bytea_parser.dart'
              graphql_type: bytea
              dart_type: String
