// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxx0vpUlHtPYfXu1AOr7T4Bj9PKSTzDzw',
    appId: '1:691649418083:web:76c41464ee013b7bd87956',
    messagingSenderId: '691649418083',
    projectId: 'uailist',
    authDomain: 'uailist.firebaseapp.com',
    storageBucket: 'uailist.appspot.com',
    measurementId: 'G-XR6J5RQPG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxEsJF3k3-ez9f2kgZoaPzkHIfzXQmTjI',
    appId: '1:691649418083:android:eeb5c200de720861d87956',
    messagingSenderId: '691649418083',
    projectId: 'uailist',
    storageBucket: 'uailist.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP1IlD9ObobmPcbbOsa0gzuT6X9Ea7gIQ',
    appId: '1:691649418083:ios:cc7c92217544b285d87956',
    messagingSenderId: '691649418083',
    projectId: 'uailist',
    storageBucket: 'uailist.appspot.com',
    iosClientId: '691649418083-9nqdu28ahf38vvtg9dbh1f67i8rl9ufn.apps.googleusercontent.com',
    iosBundleId: 'com.uailist.app',
  );
}
