-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."supermarket" add column "created_by_user_uuid" uuid
--  not null;
